### ISSUE TITLE
new logo - spacing and color

### ISSUE THREAD

**Issue by trel** [irods/irods_client_library_rirods#40]
The new rirods logo is inspired, but we should update it with proper spacing and color to be in line with the intent at https://irods.org/logo

**Comment by montesmariana** [comment]
I adapted it and post it here so that it can be changed in the next documentation update.

# PNG of the logo in gray and teal
![rirods-logo-teal](https://github.com/irods/irods_client_library_rirods/assets/54317904/8abe80e0-f35e-4065-bbb5-a70910b992b2)

# SVG of the logo in gray and teal
![rirods-logo-teal](https://github.com/irods/irods_client_library_rirods/assets/54317904/46f839e9-b62e-4a27-936a-bd44829946e1)

# SVG including the rirods logo and the irods logo in case anyone wants to do some other manipulation
![rirods-logo](https://github.com/irods/irods_client_library_rirods/assets/54317904/8dfa6981-373c-4f97-86fa-586602b0fb13)

**Comment by MartinSchobben** [comment]
Wonderful. Will include it in the next update.

**Comment by montesmariana** [comment]
You might also want to check if the new color still fits with the minty theme or some bslib variables would need to be adapted: https://pkgdown.r-lib.org/articles/customise.html#bslib-variables

**Comment by korydraughn** [comment]
Not sure if it's intended, but the font for the **rirods** text above **RIR** in image 1 is different than what is in images 2 and 3.

**Comment by montesmariana** [comment]
The first image is a PNG, so, fully an image, whereas the other 2 are SVG, so I suppose you have to open them with something that interprets the font properly (not the browser)? The font is Segoe UI and the PNG was exported from the SVG.

**Comment by korydraughn** [comment]
Got it. That makes sense.

**Comment by trel** [comment]
this looks pretty good to me.  thank you!
